srcs += files(
  'error_v/creation.f90',
  'error_v/error_v.f90',
  'error_v/passing.f90',
  'error_v/creation_wrapper.f90',
  'error_v/error_v_manager.f90',
  'error_v/error_v_wrapper.f90',
  'error_v/passing_wrapper.f90',
  'fpyfgen/base_finalisable.f90',
  'get_wavelength.f90',
  'kind_parameters.f90',
  'result/result_dp_manager.f90',
  'result/result_dp_wrapper.f90',
  'result/result_int1D.f90',
  'result/result_int_manager.f90',
  'result/result_int_wrapper.f90',
  'result/result_dp.f90',
  'result/result.f90',
  'result/result_int.f90',
  'result/result_none.f90',
)
